name = "server"
compatibility_date = "2024-09-25"
compatibility_flags = [ "nodejs_compat" ]

[vars]
MY_VAR = "my-variable"
DB_ENDPOINT = ""
DB_USERNAME = ""
DB_PASSWORD = ""
NS="techstudio"
DB="techstudio"
CF_ACCOUNT_ID=""
CF_ACCESS_KEY_ID=""
CF_SECRET_ACCESS_KEY=""
CF_ACCESS_KEY_TOKEN=""
R2_BASE_PATH=""
R2_PUBLIC_BUCKET_NAME=""


# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

[observability]
enabled = true
head_sampling_rate = 1